// This file is @generated by prost-build.
/// Request for file-based transcription
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeFileRequest {
    /// Audio data as bytes (WAV format, 16kHz, mono, 16-bit)
    #[prost(bytes = "vec", tag = "1")]
    pub audio_data: ::prost::alloc::vec::Vec<u8>,
    /// Optional: Apply custom dictionary corrections
    #[prost(bool, tag = "2")]
    pub use_dictionary: bool,
}
/// Response for file-based transcription
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeFileResponse {
    /// Transcribed text
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    /// Success indicator
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// Error message if transcription failed
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// Request for streaming transcription
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeStreamRequest {
    #[prost(oneof = "transcribe_stream_request::RequestType", tags = "1, 2")]
    pub request_type: ::core::option::Option<transcribe_stream_request::RequestType>,
}
/// Nested message and enum types in `TranscribeStreamRequest`.
pub mod transcribe_stream_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum RequestType {
        /// Audio chunk data (WAV format, 16kHz, mono, 16-bit)
        #[prost(bytes, tag = "1")]
        AudioChunk(::prost::alloc::vec::Vec<u8>),
        /// Signal that streaming is complete
        #[prost(bool, tag = "2")]
        EndOfStream(bool),
    }
}
/// Response for streaming transcription
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeStreamResponse {
    /// Indicates if this is a final result
    #[prost(bool, tag = "4")]
    pub is_final: bool,
    #[prost(oneof = "transcribe_stream_response::ResponseType", tags = "1, 2, 3")]
    pub response_type: ::core::option::Option<transcribe_stream_response::ResponseType>,
}
/// Nested message and enum types in `TranscribeStreamResponse`.
pub mod transcribe_stream_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ResponseType {
        /// Partial transcription text
        #[prost(string, tag = "1")]
        PartialText(::prost::alloc::string::String),
        /// Final transcription text (sent when stream ends)
        #[prost(string, tag = "2")]
        FinalText(::prost::alloc::string::String),
        /// Error message
        #[prost(string, tag = "3")]
        Error(::prost::alloc::string::String),
    }
}
/// Generated client implementations.
pub mod transcription_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Transcription service for speech-to-text
    #[derive(Debug, Clone)]
    pub struct TranscriptionServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TranscriptionServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TranscriptionServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TranscriptionServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TranscriptionServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Transcribe a complete audio file (non-streaming)
        pub async fn transcribe_file(
            &mut self,
            request: impl tonic::IntoRequest<super::TranscribeFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TranscribeFileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/murmure.TranscriptionService/TranscribeFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("murmure.TranscriptionService", "TranscribeFile"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Bidirectional streaming for real-time audio transcription
        pub async fn transcribe_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::TranscribeStreamRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TranscribeStreamResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/murmure.TranscriptionService/TranscribeStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("murmure.TranscriptionService", "TranscribeStream"),
                );
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod transcription_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TranscriptionServiceServer.
    #[async_trait]
    pub trait TranscriptionService: std::marker::Send + std::marker::Sync + 'static {
        /// Transcribe a complete audio file (non-streaming)
        async fn transcribe_file(
            &self,
            request: tonic::Request<super::TranscribeFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TranscribeFileResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the TranscribeStream method.
        type TranscribeStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::TranscribeStreamResponse,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        /// Bidirectional streaming for real-time audio transcription
        async fn transcribe_stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::TranscribeStreamRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::TranscribeStreamStream>,
            tonic::Status,
        >;
    }
    /// Transcription service for speech-to-text
    #[derive(Debug)]
    pub struct TranscriptionServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TranscriptionServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for TranscriptionServiceServer<T>
    where
        T: TranscriptionService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/murmure.TranscriptionService/TranscribeFile" => {
                    #[allow(non_camel_case_types)]
                    struct TranscribeFileSvc<T: TranscriptionService>(pub Arc<T>);
                    impl<
                        T: TranscriptionService,
                    > tonic::server::UnaryService<super::TranscribeFileRequest>
                    for TranscribeFileSvc<T> {
                        type Response = super::TranscribeFileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TranscribeFileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TranscriptionService>::transcribe_file(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TranscribeFileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/murmure.TranscriptionService/TranscribeStream" => {
                    #[allow(non_camel_case_types)]
                    struct TranscribeStreamSvc<T: TranscriptionService>(pub Arc<T>);
                    impl<
                        T: TranscriptionService,
                    > tonic::server::StreamingService<super::TranscribeStreamRequest>
                    for TranscribeStreamSvc<T> {
                        type Response = super::TranscribeStreamResponse;
                        type ResponseStream = T::TranscribeStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::TranscribeStreamRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TranscriptionService>::transcribe_stream(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TranscribeStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TranscriptionServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "murmure.TranscriptionService";
    impl<T> tonic::server::NamedService for TranscriptionServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
